### PR TITLE
Update breeding.js

### PR DESCRIPTION
**Pull request by Dimava**
[Shiny chance] depends on steps gained while [Shiny Charm] was active

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Why did you close it?

**Comment by Dimava** [comment]
Some more edits needed

**Comment by Ishadijcks** [comment]
Alright!

**Comment by Dimava** [comment]
Note: eggs have additional property 'shinySteps'. 
Eggs without 'shinySteps' will get it on first defeat, value depends on [Shiny Charm] state.

**Comment by gro-te** [comment]
I noticed I was late to the party and created a fix after this was submitted....
I prefer most of this solution. It does however misses a check for whether or not an egg is at it's max steps. 
This allows people to walk around with a hatch-able egg while the chance of it being a shiny increases up to the point where it is guaranteed to be a shiny.

**Comment by gro-te** [comment]
5ba13f0 doesn't seem related to this PR.

**Pull request closed without merging**
