### PR TITLE
added ".noselect" class

### PR DESCRIPTION
**Pull request by MarcoWorms**
to use on index.html "#enemyInfo"

### CODE REVIEW

**Comment by diff-by-default** [comment]
Is there a particular reason that this and #15 are not in the same PR? I understand feature branches, but these are the same feature--one won't work without the other.

**Comment by MarcoWorms** [comment]
I edited via browser and it created 2 pull requests. You are right, they should be 2 commits in the same PR, sorry about that.

**Comment by MarcoWorms** [comment]
i'm creating a merged one

**Comment by diff-by-default** [comment]
No worries, just curious. I completely forgot you could edit stuff straight from github

**Comment by MarcoWorms** [comment]
I did a merged one here https://github.com/Ishadijcks/Ishadijcks.github.io/pull/17 :)

**Pull request closed without merging**
